const images = [ { src: '../assets/images/1allieleggett.jpg', position: 'left edge', caption: 'Allie Leggett,London', captionPosition: 'caption-right', style: {'width': '700px'} },
{ src: '../assets/images/1.1AllieLeggett.jpg',
  position: 'right' },
{ src: '../assets/images/2AlanaHadid.jpg', position: 'full' },
{ src: '../assets/images/3Rafaella.jpg', position: 'left' },
{ src: '../assets/images/3.1Rafaella.jpg', position: 'right edge', caption: 'Another test caption' },
{ src: '../assets/images/3.2Rafaella.jpg', position: 'center' },
{ src: '../assets/images/3.3Rafaella.jpg', position: 'left edge' },
{ src: './assets/images/4ChloeLloyd.jpg', position: 'right' },
{ src: '../assets/images/5ArianaAnast.jpg', position: 'center' },
{ src: '../assets/images/6GeorginaGrace.jpg', position: 'left' },
{ src: '../assets/images/7CatrinaStella.jpg',
  position: 'right' },
{ src: '../assets/images/7.1CatrinaStella.jpg',
  position: 'center' },
{ src: '../assets/images/6.2CatrinaStella.jpg',
  position: 'left' },
{ src: '../assets/images/6.3CatrinaStella.jpg',
  position: 'right' },
{ src: '../assets/images/6.4CatrinaStella.jpg',
  position: 'center' },
{ src: '../assets/images/6.5CatrinaStella.jpg',
  position: 'left' },
{ src: '../assets/images/7CarolineVreeland.jpg',
  position: 'right' },
{ src: '../assets/images/8GeorginaGrace.jpg',
  position: 'center' },
{ src: '../assets/images/9WomeninCalifornia.jpg',
  position: 'left' },
{ src: '../assets/images/9.1WomeninCalifornia.jpg',
  position: 'right' },
{ src: '../assets/images/10.2LauraColeman.jpg',
  position: 'center' },
{ src: '../assets/images/10.1LauraColeman.jpg',
  position: 'left' },
{ src: '../assets/images/10LauraColeman.jpg',
  position: 'right' },
{ src: '../assets/images/11catherinedunlop.jpg',
  position: 'center' },
{ src: '../assets/images/11.1CatherineDunlop.jpg',
  position: 'left' },
{ src: '../assets/images/11.2CatherineDunlop.jpg',
  position: 'right' },
{ src: '../assets/images/11.3CatherineDunlop.jpg',
  position: 'center' },
{ src: '../assets/images/11.5CatherineDunlop.jpg',
  position: 'left' },
{ src: '../assets/images/11.6CatherineDunlop.jpg',
  position: 'right' },
{ src: '../assets/images/17Charlotte.jpg', position: 'center' },
{ src: '../assets/images/12.1GeorginaGrace.jpg',
  position: 'left' },
{ src: '../assets/images/5.1CarolineVreeland.jpg',
  position: 'right' },
{ src: '../assets/images/13TessJantschek.jpg',
  position: 'center' },
{ src: '../assets/images/14.5LeilaYavari.jpg',
  position: 'left' },
{ src: '../assets/images/14LeilaYavari.jpg', position: 'right' },
{ src: '../assets/images/14.2LeilaYavari.jpg',
  position: 'center' },
{ src: '../assets/images/14.4LeilaYavari.jpg',
  position: 'left' },
{ src: '../assets/images/14.6LeilaYavari.jpg',
  position: 'right' },
{ src: '../assets/images/14.3LeilaYavari.jpg',
  position: 'center' },
{ src: '../assets/images/14.1LeilaYavari.jpg',
  position: 'left' },
{ src: '../assets/images/16JessicaBuchanan.jpg',
  position: 'right' },
{ src: '../assets/images/15.2VeronicaTaylor.jpg',
  position: 'center' },
{ src: '../assets/images/15VeronicaTaylor.jpg',
  position: 'left' },
{ src: '../assets/images/15.1VeronicaTaylor.jpg',
  position: 'right' } ];

export default images;